---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/8/28 11:32
---



--评星界面枚举
EnumRatinglevel={}
--游戏内评星系统
EnumRatinglevel.InGame = 1;
--平台评星系统界面
EnumRatinglevel.IGGPlatform = 2;
--平台评星系统 完成界面
EnumRatinglevel.IGGPlatformComplete = 3;
--反馈建议界面
EnumRatinglevel.Feedback = 4;
--反馈建议 输入界面
EnumRatinglevel.FeedbackInput = 5;
--反馈建议 提交后界面
EnumRatinglevel.FeedbackSend = 6;



--全局枚举
BookType={};
--书本分类
BookType.Romance=1;
BookType.LGBT=2;
BookType.Action=3;
BookType.Youth=4;
BookType.Adventure=5;
BookType.Drama=6;
BookType.Comedy=7;
BookType.Horror=8;
BookType.Eighteen=9;
BookType.Fantasy=10;
BookType.Suspense=11;
BookType.Others=12;


--排行榜枚举
RankType={};
--平台书本排行
RankType.Platform=1;
--新书本排行
RankType.Newbook=2;
--人气排行
RankType.Popularity=3;


MainDown={}
--主界面 Toogle
MainDown.HomeToggle=1;
--搜索界面 Toggle
MainDown.SearchToggle=2;
--创作界面 Toogle
MainDown.CommunityToggle=3;
--活动奖励 Toogle
MainDown.RwardToggle=4;
--个人中心 Toogle
MainDown.ProfileToggle=5;

--装扮
DressUp={}
--头像
DressUp.Avatar=1;
--头像框
DressUp.AvatarFrame=2;
--弹幕框
DressUp.BarrageFrame=3;
--评论框
DressUp.CommentFrame=4;

--埋点类型
BuriedPoint_bookType={}
--推荐
BuriedPoint_bookType.Recommen="home_2";
--推荐
BuriedPoint_bookType.MyBooks="home_3";
--LGBT
BuriedPoint_bookType.LGBT="home_4";
--Romance
BuriedPoint_bookType.LGBT="home_5";
--Suspense
BuriedPoint_bookType.Suspense="home_6";
--周更
BuriedPoint_bookType.WeeklyUpdate="home_7";



--【获取限时活动状态】 是哪个页面
BookFree_UI={}
--主界面
BookFree_UI.MainForm = 1;
--主界面


--活动类型
EnumActivity={}
--彩蛋
EnumActivity.ColoredEgg=1;
--转盘抽奖
EnumActivity.SpinDraw=2;
--全书免费
EnumActivity.FreeKey=3;


EActivityPanel={}

--【签到】
EActivityPanel.SignIn=1;
--【在线阅读时长】
EActivityPanel.ReadTime=2;
--【每日任务】
EActivityPanel.DailyTasks=3;
--【看广告】
EActivityPanel.FreeReward=4;



EStoryList={}

EStoryList.None=0;
--【最受欢迎】
EStoryList.MostPopular=1;
--【最新更新】
EStoryList.LatestRelease=2;
--【我写作的故事】
EStoryList.MyWriterList=3;
--【历史看过的故事】
EStoryList.HistoryList=4;
--【别的作者写的书】
EStoryList.WriterList=5;
