source 'https://github.com/CocoaPods/Specs.git'

target 'Unity-iPhone' do
  #FacebookSDK\Plugins\Editor\Dependencies.xml
  pod 'FBSDKCoreKit', '~> 6.2'
  pod 'FBSDKLoginKit', '~> 6.2'
  pod 'FBSDKShareKit', '~> 6.2'
  pod 'FBSDKGamingServicesKit', '~> 6.2'
  pod 'Firebase/Analytics', '6.21.0'  
  pod 'Firebase/Core', '6.21.0'
  pod 'Fabric', '1.10.2'
  pod 'Crashlytics', '3.14.0'
  pod 'Firebase/Crashlytics', '6.21.0'
  
  
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationUnity'
  pod 'GoogleMobileAdsMediationFacebook', '6.0.0.0'
  pod 'GoogleMobileAdsMediationTestSuite'
  
end
