platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Unity-iPhone' do
  pod 'FBSDKCoreKit', '8.2.0'
  pod 'FBSDKLoginKit', '8.2.0'
  pod 'FBSDKShareKit', '8.2.0'
  pod 'FBSDKGamingServicesKit', '8.2.0'
  pod 'Firebase/Analytics', '7.4.0'
  pod 'Firebase/Core', '7.4.0'
  pod 'Firebase/Crashlytics'  
  pod 'mob_linksdk_pro'
  
  pod 'Google-Mobile-Ads-SDK', '7.69.0'
  pod 'GoogleMobileAdsMediationUnity', '3.6.0.0'
  pod 'GoogleMobileAdsMediationFacebook', '6.2.0.0'
  #pod 'GoogleMobileAdsMediationTestSuite'
  
end

